######################## default configuration ####################
baseurl: "http://localhost:3000"
# languageCode: nl-be
# languageLang: nl
# title: Hoop doet leven
# # RSS, categories and tags disabled for an easy start
# # See configuration options for more details:
# # https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "#HoopDoetLeven"
  description: "#HoopDoetLeven zoekt met het Koninklijk Paleis verhalen van helden tijdens de coronalockdown. Ken jij iemand die een kleine of grote heldendaad heeft verricht? Laat het ons weten!"
  ogImage: "/img/OG-NL.png"
  hashTag: "#HoopDoetLeven"
  analyticsCode: "UA-160941697-5"
  logo: 
    src: "/img/hoopdoetlevenNL.png"
    width: 199
    height: 182
  tagLine: 
    hope: "Hoop"
    brings: "Doet"
    life: "Leven"
  copyright: "Made with ❤️ by [Coronadenktank](https://www.coronadenktank.be/)"
  doormatInfo: "De Coronadenktank is een burgerbeweging die alternatieve oplossingen bedenkt en bouwt om het leed van COVID-19 te verzachten en de verspreiding van SARS-CoV-2 te verminderen. Al snel na de Belgische lockdown, half maart 2020, is de burgerbeweging op enkele dagen uitgegroeid van enkelingen naar een netwerk van duizenden burgers die hun brede expertise bij elkaar gelegd hebben om oplossingen te bouwen. Van IT’ers tot naaisters en van spoedartsen tot communicatiespecialisten, iedereen werkt solidair, flexibel en doelgericht samen."
  apiLocation: https://localhost:8443
  recaptchaKey: 6LdU3KoZAAAAAGdoYTdxt7JYa5uYaiYnkubbnaik

############################## navigation ###############################
SectionPagesMenu: main
menu: 
  main:
    - identifier: home
      name: Home
      url: /
      weight: 5
  footer:
    - identifier: disclaimer
      name: Disclaimer
      url: disclaimer
      weight: 10

############################## languages ##########################
defaultContentLanguage: nl
defaultContentLanguageInSubdir: true
disableLanguages: ["en"]

languages:
  nl:
    weight: 1
    languageName: Nederlands
    languageCode: nl
    contentDir: content/nl
    title: "#HoopDoetLeven"
    baseurl: "http://localhost:3000/nl"
    ogImage: "/img/OG-NL.png"
    hashTag: "#HoopDoetLeven"
    analyticsCode: "UA-160941697-5"
    tagLine: 
      hope: "Hoop"
      brings: "Doet"
      life: "Leven"
  en:
    weight: 2
    languageName: English
    languageCode: en
    contentDir: content/en
    tag: HopeBringsLife
    title: Home
    baseurl: "http://localhost:3000/en"
    description: ""
    ogImage: "/img/OGNL.png"
    hashTag: "#HopeBringsLife"
    analyticsCode: "UA-160941697-5"
    tagLine: 
      hope: "Hope"
      brings: "Brings"
      life: "Life"
    doormatInfo: "The Corona crisis was a tough challenge for everyone. We all know someone with a punishment story. A story about creativity and resilience. A story full of hope and connectedness. On the occasion of the national holiday, we would like to hear those stories, tell them and share them with everyone."
  fr:
    weight: 2
    languageName: Français
    languageCode: fr
    contentDir: content/fr
    title: "#PleindEspoir"
    baseurl: "http://localhost:3000/fr"
    description: "#PleinDEspoir et le Palais Royal recherchent des histoires de héros qui ont fait la différence pendant le confinement. Vous connaissez quelqu'un qui a accompli un acte héroïque, qu'il soit petit ou grand ? Faites-le nous savoir !"
    ogImage: "/img/OG-FR.png"
    hashTag: "#PleindEspoir"
    analyticsCode: "UA-160941697-6"
    logo: 
      src: "/img/hoopdoetlevenFR.png"
      width: 170
      height: 184
    tagLine:
      hope: "Plein"
      brings: "d"
      life: "Espoir"
    doormatInfo: "Le Coronadenktank est un mouvement civil qui conçoit et construit des solutions alternatives pour soulager la souffrance de COVID19 et réduire la propagation du SRAS-CoV-2. Peu après le confinement de la Belgique à la mi-mars 2020, le mouvement citoyen est passé de quelques individus à un réseau de milliers de citoyens qui ont mis  à disposition leur vaste expertise pour construire des solutions. Des professionnels de l'informatique aux couturières, des urgentistes aux spécialistes de la communication, tous travaillent ensemble dans un esprit de solidarité, de flexibilité et de détermination."
    menu: 
      main:
        - identifier: home
          name: Acceuil
          url: /
          weight: 5
      footer:
        - identifier: disclaimer
          name: Disclaimer
          url: disclaimer
          weight: 10
  de:
    weight: 2
    languageName: Deutsch
    languageCode: de
    contentDir: content/de
    title: "#VollerHoffnung"
    baseurl: "http://localhost:3000/de"
    description: ""
    ogImage: "/img/OGDE.png"
    hashTag: "#VollerHoffnung"
    analyticsCode: "UA-160941697-7"
    logo: 
      src: "/img/hoopdoetlevenDE.png"
      width: 218
      height: 187
    tagLine: 
      hope: "Voller"
      brings: ""
      life: "Hoffnung"
    doormatInfo: "Der Coronadenktank ist eine Bürgerbewegung, die alternative Lösungen entwirft und entwickelt, um das Leiden von COVID19 zu lindern und die Ausbreitung von SARS-CoV-2 einzudämmen. Kurz nach der Eindämmung Belgiens Mitte März 2020 wuchs die Bürgerbewegung von einigen wenigen Einzelpersonen zu einem Netzwerk von Tausenden von Bürgern, die ihr enormes Fachwissen bündelten, um Lösungen zu erarbeiten. Von IT-Fachleuten bis zu Näherinnen, von Notärzten bis zu Kommunikationsspezialisten arbeiten alle im Geiste der Solidarität, Flexibilität und Entschlossenheit zusammen."
    menu: 
      main:
        - identifier: home
          name: Startseite
          url: /
          weight: 5
      footer:
        - identifier: disclaimer
          name: Disclaimer
          url: disclaimer
          weight: 10
