######################## default configuration ####################
baseurl: "/"
# languageCode: nl-be
# languageLang: nl
# title: Hoop doet leven
# # RSS, categories and tags disabled for an easy start
# # See configuration options for more details:
# # https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: Home
  description: Beschrijving
  hashTag: "#HoopDoetLeven"
  logo: 
    src: "/img/hoopdoetlevenNL.png"
    width: 199
    height: 182
  tagLine: 
    hope: "Hoop"
    brings: "Doet"
    life: "Leven"
  copyright: "&copy; Copyright 2020"
  doormatInfo: "De Corona Denktank is een burgerbeweging die alternatieve oplossingen bedenkt en bouwt om het leed van COVID19 te verzachten en de verspreiding van SARS-CoV-2 te verminderen. Al snel na de Belgische lockdown, half maart 2020, is de burgerbeweging op enkele dagen uitgegroeid van enkelingen naar een netwerk van duizenden burgers die hun brede expertise bij elkaar gelegd hebben om oplossingen te bouwen. Van IT’ers tot naaisters en van spoedartsen tot communicatiespecialisten, iedereen werkt solidair, flexibel en doelgericht samen."

############################## languages ##########################
defaultContentLanguage: nl
disableLanguages: ["en"]

languages:
  nl:
    weight: 1
    languageName: Nederlands
    languageCode: nl
    contentDir: content/nl
    title: Home
    description: ""
    hashTag: "#HoopDoetLeven"
    tagLine: 
      hope: "Hoop"
      brings: "Doet"
      life: "Leven"
  en:
    weight: 2
    languageName: English
    languageCode: en
    contentDir: content/en
    tag: HopeBringsLife
    title: Home
    description: ""
    hashTag: "#HopeBringsLife"
    tagLine: 
      hope: "Hope"
      brings: "Brings"
      life: "Life"
    doormatInfo: "The Corona crisis was a tough challenge for everyone. We all know someone with a punishment story. A story about creativity and resilience. A story full of hope and connectedness. On the occasion of the national holiday, we would like to hear those stories, tell them and share them with everyone."
  fr:
    weight: 2
    languageName: Français
    languageCode: fr
    contentDir: content/fr
    title: Home
    description: ""
    hashTag: "#PleindEspoir"
    logo: 
      src: "/img/hoopdoetlevenFR.png"
      width: 170
      height: 184
    tagLine:
      hope: "Plein"
      brings: "d"
      life: "Espoir"
  de:
    weight: 2
    languageName: Deutsch
    languageCode: de
    contentDir: content/de
    title: Home
    description: ""
    hashTag: "#VollerHoffnung"
    logo: 
      src: "/img/hoopdoetlevenDE.png"
      width: 218
      height: 187
    tagLine: 
      hope: "Voller"
      brings: ""
      life: "Hoffnung"

############################## navigation ###############################
menu: 
  main:
    - identifier: stories
      name: Verhalen
      url: verhalen
      weight: 10
    - identifier: participate
      name: Meedoen
      url: meedoen
      weight: 20
  doormat:
    - identifier: stories
      name: Verhalen
      url: verhalen
      weight: 10
    - identifier: participate
      name: Meedoen
      url: meedoen
      weight: 10
    - identifier: styleguide
      name: Style guide
      url: styleguide
      weight: 100
  footer:
    - identifier: disclaimer
      name: Disclaimer
      url: disclaimer
      weight: 10
