######################## default configuration ####################
baseurl: "/"
# languageCode: nl-be
# languageLang: nl
# title: Hoop doet leven
# # RSS, categories and tags disabled for an easy start
# # See configuration options for more details:
# # https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: Hoop doet leven
  description: Beschrijving
  hashTag: "#HoopDoetLeven"
  tagLine: 
    hope: "Hoop"
    brings: "Doet"
    life: "Leven"
  copyright: "&copy; Copyright 2020"
  doormatInfo: "De Coronacrisis was voor iedereen een stevige uitdaging. We kennen allemaal wel iemand met een straf verhaal. Een verhaal over creativiteit en veerkracht. Een verhaal vol hoop en verbondenheid. Naar aanleiding van de nationale feestdag willen we die verhalen graag horen, doorvertellen en zo met iedereen delen."

############################## languages ##########################
defaultContentLanguage: nl
disableLanguages: ["de", "fr"]

languages:
  nl:
    weight: 1
    languageName: Nederlands
    languageCode: nl
    contentDir: content/nl
    title: Hoop doet leven
    description: Beschrijving
    hashTag: "#HoopDoetLeven"
    tagLine: 
      hope: "Hoop"
      brings: "Doet"
      life: "Leven"
    menu:
      main:
        - identifier: about
          name: Over
          url: /over
          weight: 30
        - identifier: nominate
          name: Nomineer iemand
          url: /nomineer
          weight: 50
        # - identifier: contact
        #   name: Contacteer ons
        #   url: /contact
        #   weight: 100
      doormat:
        - identifier: about
          name: Over
          url: /over
          weight: 30
        - identifier: nominate
          name: Nomineer iemand
          url: /nomineer
          weight: 50
        - identifier: styleguide
          name: Stijlgids
          url: /styleguide
          weight: 100
        # - identifier: contact
        #   name: Contacteer ons
        #   url: /contact
        #   weight: 100
      footer:
        - identifier: disclaimer
          name: Disclaimer
          url: /disclaimer
          weight: 10
        - identifier: privacy
          name: Privacy
          url: /privacy
          weight: 10
   
  en:
    weight: 2
    languageName: English
    languageCode: en
    contentDir: content/en
    tag: HopeBringsLife
    title: Hope brings life
    description: some description stuff
    hashTag: "#HopeBringsLife"
    tagLine: 
      hope: "Hope"
      brings: "Brings"
      life: "Life"
    doormatInfo: "The Corona crisis was a tough challenge for everyone. We all know someone with a punishment story. A story about creativity and resilience. A story full of hope and connectedness. On the occasion of the national holiday, we would like to hear those stories, tell them and share them with everyone."
  fr:
    weight: 2
    languageName: Fran√ßais
    languageCode: fr
    contentDir: content/fr
    title: Plein d'espoir
    description: ""
    hashTag: "#PleindEspoir"
    tagLine:
      hope: "Plein"
      brings: "d"
      life: "Espoir"
  de:
    weight: 2
    languageName: Deutsch
    languageCode: de
    contentDir: content/de
    title: Hoffnung zum Leben
    description: ""
    hashTag: "#HoffnungZumLeben"
    tagLine: 
      hope: "Hoffnung"
      brings: "Zum"
      life: "Leben"

############################## navigation ###############################
menu: 
  main:
    - identifier: about
      name: About
      url: /about
      weight: 30
    - identifier: nominate
      name: Nominate someone
      url: /nominate
      weight: 50
    # - identifier: contact
    #   name: Contact
    #   url: /contact
    #   weight: 100
  doormat:
    - identifier: about
      name: About
      url: /about
      weight: 30
    - identifier: nominate
      name: Nominate someone
      url: /nominate
      weight: 50
    - identifier: styleguide
      name: Style guide
      url: /styleguide
      weight: 100
    # - identifier: contact
    #   name: Contact
    #   url: /contact
    #   weight: 100
  footer:
    - identifier: disclaimer
      name: Disclaimer
      url: /disclaimer
      weight: 10
    - identifier: privacy
      name: Privacy
      url: /privacy
      weight: 10
